src/books/models.py
import flask_whooshalchemy
from run import app, db


class Book(db.Model):
    __tablename__ = 'books'
    __searchable__ = ['title']

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(256))

    def __repr__(self):
        return '<Book title %r>' % (self.title)


flask_whooshalchemy.whoosh_index(app, Book)

src/books/forms/forms.py
from wtforms import TextField, Form
from wtforms.validators import Required


class CreateBookForm(Form):
    title = TextField('title', validators = [Required()])


class AddAuthorForm(Form):
    author_id = TextField('author_id', validators = [Required()])


class SearchForm(Form):
    search = TextField('search', validators = [Required()])

src/books/__init__.py
from flask import Blueprint

books = Blueprint('books', __name__, template_folder='templates', static_folder='static', static_url_path='/static/books')
import views

src/books/views.py
from books.forms.forms import CreateBookForm, AddAuthorForm, SearchForm
from books.service.book_service import BookService
from authors.service.author_service import AuthorService
from flask import request, redirect, render_template, g
import flask
from books import books
from flask.ext.login import login_required


author_service = AuthorService()
book_service = BookService()

@books.route('/create_book', methods=['GET', 'POST'])
@login_required
def create_book():
    form = CreateBookForm(request.form)
    if request.method == 'POST' and form.validate():
        book_service.create_book(form.title.data)
        return flask.jsonify({'result': True})
    return render_template('create_book.html', title='Create Book', form=form, book=None)

@books.route('/books')
def books_list():
    books = book_service.get_all()
    return render_template('books.html', books=books)

@books.route('/books/<book_id>')
def book(book_id):
    book = book_service.get_by_id(book_id)
    return render_template('book.html', book=book)

@books.route('/delete/book/<book_id>')
@login_required
def delete_book(book_id):
    book_service.delete_book(book_id)
    return redirect('/books')

@books.route('/edit_book', methods=['GET', 'POST'])
@login_required
def edit_book():
    form = CreateBookForm(request.form)
    book = None
    if request.method == 'GET':
        book = book_service.get_by_id(request.args.get('book'))
        form = CreateBookForm(obj=book)
    if request.method == 'POST' and form.validate():
        book = book_service.get_by_id(request.form.get('book'))
        book_service.edit_book(book, form.title.data)
        return flask.jsonify({'result': True})
    return render_template('create_book.html', title='Create Book', form=form, book=book)

@books.route('/book/author/add', methods=['GET', 'POST'])
@login_required
def add_author_book():
    form = AddAuthorForm(request.form)
    book = None
    authors = author_service.get_all()
    if request.method == 'GET':
        book = book_service.get_by_id(request.args.get('book'))
    if request.method == 'POST' and form.validate():
        book = book_service.get_by_id(request.form.get('book'))
        author = author_service.get_by_id(form.author_id.data)
        author.add_book(book)
        return flask.jsonify({'result': True})
    return render_template('add_author.html', form=form, book=book, authors=authors)

@books.route('/book/author/delete')
@login_required
def delete_author_book():
    book = book_service.get_by_id(request.args.get('book'))
    author = author_service.get_by_id(request.args.get('author'))
    author.delete_book(book)
    return flask.jsonify({'result': True})

@books.before_request
def before_request():
    g.search_form = SearchForm()

@books.route('/search', methods=['GET', 'POST'])
def search():
    form = SearchForm(request.form)
    if not form.validate() and request.method != 'POST':
        return redirect('/')
    query = form.search.data
    results = book_service.book_whoosh_search(query)
    authors = author_service.author_whoosh_search(query)
    for author in authors:
        results.extend(author.books.all())

    return render_template('books.html', books=set(results))

src/books/templates/add_author.html
    <form method="post" action="{{ url_for('books.add_author_book') }}" name="add_author" class="add-book-author-form">
        {{form.hidden_tag}}
        <p>Choose author:
            <select id="author_id" name="author_id">
                {% for author in authors %}
                <option value="{{ author.id }}">{{ author.name }}</option>
                {% endfor %}
            </select>
        </p>

        <p><input type="submit" value="Save" class="save-add-book-author" data-book="{{ book.id }}"></p>
        <p><input type="submit" value="Cancel" class="cancel-add-book-author"></p>
    </form>

src/books/templates/book.html
{% extends 'base.html' %}

{% block css_content %}
    <link href="{{ url_for('books.static', filename='css/books.css') }}" rel="stylesheet">
{% endblock %}

{% block js_content %}
   <script type="text/javascript">
       Library.data.main.edit_book_url = "{{ url_for('books.edit_book') }}"
       Library.data.main.add_author_book_url = "{{ url_for('books.add_author_book') }}"
       Library.data.main.delete_author_book_url = "{{ url_for('books.delete_author_book') }}"
   </script>
{% endblock %}

{% block content %}
    <div class="title-block">Book: {{ book.title }}
        {% if current_user.is_authenticated() and current_user.role < 2 %}
        <div class="book-buttons">
            <div class="edit-book-button" data-book="{{ book.id }}">Edit</div>
            <div class="delete-book-button"><a href="{{ url_for('books.delete_book', book_id=book.id) }}">Delete</a></div>
        </div>
        {% endif %}
    </div>
    <p>Authors:</p>
    {% for author in book.authors %}
        <div class="author-name-block" data-author="{{ author.id }}">
            {{ author.name }}
            {% if current_user.is_authenticated() and current_user.role < 2 %}
                <div class="delete-book-author-button" data-book="{{ book.id }}" data-author="{{ author.id }}">Delete</div>
            {% endif %}
        </div>
    {% endfor %}

    {% if current_user.is_authenticated() and current_user.role < 2 %}
        <div class="add-book-author-button" data-book="{{ book.id }}">Add author</div>
    {% endif %}

{% endblock %}

src/books/templates/books.html
{% extends 'base.html' %}

{% block css_content %}
    <link href="{{ url_for('books.static', filename='css/books.css') }}" rel="stylesheet">
{% endblock %}

{% block js_content %}
   <script type="text/javascript">
       Library.data.main.add_book_url = "{{ url_for('books.create_book') }}"
   </script>
{% endblock %}

{% block content %}
<div class="title-block">Books</div>
{% if current_user.is_authenticated() and current_user.role < 2 %}
    <div class="add-book-button">Add book</div>
{% endif %}
{% for book in books %}
    <p>
        <a href="{{ url_for('books.book', book_id=book.id) }}">{{ book.title }}</a>.
        Authors:
        {% for author in book.authors %}
            {{ author.name }},
        {% endfor %}
    </p>
{% endfor %}
{% if not books %}
    <h3>There are no books!</h3>
{% endif %}
{% endblock %}

src/books/templates/create_book.html
<form method="post" action="{{ url_for('books.create_book') }}" name="create_book" class="create-book-form">
    {{form.hidden_tag}}
    <p>Enter book title: {{ form.title }}</p>
    {% for error in form.title.errors %}
        <p>{{ error }}</p>
    {% endfor %}

    <p><input type="submit" value="Save" class="save-add-book" data-book="{{ book.id }}"></p>
    <p><input type="submit" value="Cancel" class="cancel-add-book"></p>
</form>