src/authors/models.py
from books.models import Book
import flask_whooshalchemy
from run import app, db

books = db.Table('books_authors',
                 db.Column('book_id', db.Integer, db.ForeignKey('books.id')),
                 db.Column('author_id', db.Integer, db.ForeignKey('authors.id'))
)


class Author(db.Model):
    __tablename__ = 'authors'
    __searchable__ = ['name']

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64))
    books = db.relationship(Book, secondary=books,
                            lazy='dynamic',
                            primaryjoin=(books.c.author_id == id),
                            secondaryjoin=(books.c.book_id == Book.id),
                            backref=db.backref('authors', lazy='dynamic'))

    def __repr__(self):
        return '<Author %r>' % (self.name)

    def is_author(self, book):
        return self.books.filter(books.c.book_id == book.id).count() > 0

    def add_book(self, book):
        if not self.is_author(book):
            self.books.append(book)
            return self

    def delete_book(self, book):
        if self.is_author(book):
            self.books.remove(book)
            return self


flask_whooshalchemy.whoosh_index(app, Author)

src/authors/forms/forms.py
from wtforms import TextField, Form
from wtforms.validators import Required


class CreateAuthorForm(Form):
    name = TextField('name', validators=[Required()])

src/authors/__init__.py
from flask import Blueprint

authors = Blueprint('authors', __name__, template_folder='templates', static_folder='static', static_url_path='/static/authors')
import views

src/authors/views.py
from books.forms.forms import SearchForm
import flask
from authors.forms.forms import CreateAuthorForm
from flask import render_template, redirect, request, g
from authors.service.author_service import AuthorService
from authors import authors
from flask.ext.login import login_required

author_service = AuthorService()

@authors.before_request
def before_request():
    g.search_form = SearchForm()


@authors.route('/create_author', methods=['GET', 'POST'])
@login_required
def create_author():
    form = CreateAuthorForm(request.form)
    if request.method == 'POST' and form.validate():
        author_service.create_author(form.name.data)
        return flask.jsonify({'result': True})
    return render_template('create_author.html', title='Create Author', form=form, author=None)

@authors.route('/authors')
def authors_list():
    authors = author_service.get_all()
    return render_template('authors.html', authors=authors)

@authors.route('/authors/<author_id>')
def author(author_id):
    author = author_service.get_by_id(author_id)
    return render_template('author.html', author=author)

@authors.route('/delete/author/<author_id>')
@login_required
def delete_author(author_id):
    author_service.delete_author(author_id)
    return redirect('/authors')

@authors.route('/edit_author', methods=['GET', 'POST'])
@login_required
def edit_author():
    form = CreateAuthorForm(request.form)
    author = None
    if request.method == 'GET':
        author = author_service.get_by_id(request.args.get('author'))
        form = CreateAuthorForm(obj=author)
    if request.method == 'POST' and form.validate():
        author = author_service.get_by_id(request.form.get('author'))
        author_service.edit_author(author, form.name.data)
        return flask.jsonify({'result': True})
    return render_template('create_author.html', title='Create Author', form=form, author=author)

src/authors/templates/author.html
{% extends 'base.html' %}


{% block css_content %}
    <link href="{{ url_for('authors.static', filename='css/author.css') }}" rel="stylesheet">
{% endblock %}

{% block js_content %}
   <script type="text/javascript">
       Library.data.main.edit_author_url = "{{ url_for('authors.edit_author') }}"
   </script>
{% endblock %}

{% block content %}
    <div class="title-block">Author: {{ author.name }}
        {% if current_user.is_authenticated() and current_user.role < 2 %}
            <div class="author-buttons">
                <div class="edit-author-button" data-author="{{ author.id }}">Edit</div>
                <div class="delete-author-button"><a href="{{ url_for('authors.delete_author', author_id=author.id) }}">Delete</a></div>
            </div>
        {% endif %}
    </div>

    <p>Books:</p>
    {% for book in author.books %}
        <p><a href="{{ url_for('books.book', book_id=book.id) }}">{{book.title}}</a></p>
    {% endfor %}
{% endblock %}

src/authors/templates/authors.html
{% extends 'base.html' %}


{% block css_content %}
    <link href="{{ url_for('authors.static', filename='css/author.css') }}" rel="stylesheet">
{% endblock %}

{% block js_content %}
   <script type="text/javascript">
       Library.data.main.add_author_url = "{{ url_for('authors.create_author') }}"
   </script>
{% endblock %}

{% block content %}
    <div class="title-block">Authors</div>
    {% if current_user.is_authenticated() and current_user.role < 2 %}
        <div class="add-author-button">Add author</div>
    {% endif %}
    {% for author in authors %}
        <p><a href="{{ url_for('authors.author', author_id=author.id)}}">{{ author.name }}</a></p>
    {% endfor %}
{% endblock %}

src/authors/templates/create_author.html
<form method="post" action="{{ url_for('authors.create_author') }}" name="create_author" class="create-author-form">
    {{form.hidden_tag}}
    <p>Enter author name: {{ form.name }}</p>
    {% for error in form.name.errors %}
        <p>{{ error }}</p>
    {% endfor %}

    <p><input type="submit" value="Save" class="save-add-author" data-author="{{ author.id }}"></p>
    <p><input type="submit" value="Cancel" class="cancel-add-author"></p>
</form>