src/users/models.py
from run import db

ROLE_ADMIN = 0
ROLE_EDITOR = 1
ROLE_USER = 2


class User(db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), unique=True, index=True)
    password = db.Column(db.String(64))
    role = db.Column(db.SmallInteger, default = ROLE_USER)

    def is_authenticated(self):
        return True

    def is_active(self):
        return True

    def is_anonymous(self):
        return False

    def get_id(self):
        return unicode(self.id)

    def __repr__(self):
        return '<User %r>' % (self.username)

src/users/forms/forms.py
from wtforms import TextField, Form, PasswordField
from wtforms.validators import Required, Length


class UserForm(Form):
    username = TextField('username', validators=[Required(), Length(min=4, max=25)])
    password = PasswordField('password', validators=[Required(), Length(min=4, max=25)])

src/users/__init__.py
from flask import Blueprint

users = Blueprint('users', __name__, template_folder='templates', static_folder='static', static_url_path='/static/users')
import views

src/users/views.py
from books.forms.forms import SearchForm
from flask import request, render_template, g
from flask.ext.login import login_required, logout_user, redirect, login_user
from users import users
from users.forms.forms import UserForm
from users import models
from users.service.user_service import UserService

user_service = UserService()

@users.before_request
def before_request():
    g.search_form = SearchForm()

@users.route('/')
def index():
    form = UserForm()
    form_login = UserForm()
    users = user_service.get_all()
    return render_template('index.html', form=form, form_login=form_login, users=users)

@users.route('/login_user', methods=['GET', 'POST'])
def login():
    form = UserForm()
    form_login = UserForm(request.form)
    if request.method == 'POST' and form_login.validate():
        user = user_service.get_by_username_password(form_login.username.data, form_login.password.data)
        if user:
            login_user(user)
            return redirect('/authors')
        else:
            return redirect('/')
    return render_template('index.html', title='Create User', form_login=form_login, form=form)

@users.route('/create_user', methods=['GET', 'POST'])
def create_user():
    form = UserForm(request.form)
    form_login = UserForm()
    if request.method == 'POST' and form.validate():
        user = user_service.create_user(form.username.data, form.password.data)
        if user:
            login_user(user)
        return redirect('/')
    return render_template('index.html', title='Create User', form=form, form_login=form_login)

@users.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect('/')

src/users/templates/base.html
<!DOCTYPE html>
<head>
    <link href="{{ url_for('users.static', filename='css/main.css') }}" rel="stylesheet">

    <script src="{{ url_for('users.static', filename='js/jquery-2.1.3.min.js') }}" type="text/javascript"></script>
    <script src="{{ url_for('users.static', filename='js/main.js') }}" type="text/javascript"></script>

    {% block js_content %}
    {% endblock %}


    {% block css_content %}
    {% endblock %}
</head>
<body>
<div class="navbar">
    <div class="container">
        <ul>
            <li><a href="{{ url_for('users.index') }}">Home</a></li>
            <li><a href="{{ url_for('authors.authors_list') }}">Authors</a></li>
            <li><a href="{{ url_for('books.books_list') }}">Books</a></li>
            {% if current_user.is_authenticated() %}
            <li class="search-block">
                <form action="{{url_for('books.search')}}" method="POST" name="search">
                    {{ g.search_form.search }}
                    <input type="submit" value="Search"></form>
            </li>
            {% endif %}
        </ul>
    </div>
</div>
<div class="container">
    <div class="content-block">
        {% block content %}
        {% endblock %}
    </div>
</div>
</body>
</html>

src/users/templates/index.html
{% extends 'base.html' %}

{% block content %}
        {% if current_user.is_authenticated() %}
            Hi {{ current_user.username }}! <div class="logout-user"><a href="{{ url_for('users.logout') }}">Logout</a></div>

            {% if current_user.role == 0 %}
                {% for user in users %}
                    <p>{{ user.username }}, role: {{ user.role }}</p>
                {% endfor %}
            {% endif %}
        {% else %}
            <p>Username: editor</p>
            <p>Password: editor, can create, edit and delete items.</p>
            <p>U: user</p>
            <p>P: user, can read and use search.</p>
            <p>All new users can only read and use search by default.</p>
            <div class="login-block">
                <p>Login:</p>
                <form class="user-form" action="{{ url_for('users.login') }}" method="post">
                    {{ form_login.username }}
                    {% for error in form_login.username.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                    {{ form_login.password }}
                    {% for error in form_login.password.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                    <input type="submit" value="Login" />
                </form>
            </div>
            <div class="signup-block">
                <p>Sign Up</p>
                <form class="user-form" action="{{ url_for('users.create_user') }}" method="post">
                    {{ form.username }}
                    {% for error in form.username.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                    {{ form.password }}
                    {% for error in form.password.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                    <input type="submit" value="Sing Up" />
                </form>
            </div>
        {% endif %}

{% endblock %}